---
title: "Lecture 6: Data"
---

Data in julia means: `DataFrames.jl` and friends.

New users are adivsed to start with the [new users section](https://dataframes.juliadata.org/stable/man/basics/#First-Steps-with-DataFrames.jl) in the manual. I advise you to go through that.

In class, instead, we will take the deep dive into the DataFrames.jl package with a showcase.

There is a notebook for you [here](https://github.com/floswald/DataFrames-Showcase)

## Important Packages for data

1. DataFrames.jl
2. [DataFramesMeta.jl](https://juliadata.org/DataFramesMeta.jl/stable/)
3. [Chain.jl](https://github.com/jkrumbiegel/Chain.jl)
4. [Chevrons](https://github.com/cjdoris/Chevrons.jl)

## Notebooks

1. DataFrames Showcase [here](https://github.com/floswald/DataFrames-Showcase)
2. Econ-inspired showcase [here](https://raw.githubusercontent.com/floswald/CompEcon/refs/heads/main/notebooks/week7/notebook.jl). Notice you need to also download the data in the same directory.

## Further DataFrames.jl Resources

1. [The Manual](https://dataframes.juliadata.org/stable/) is very well done, and lists a bunch of good resources on the landing page.
2. [The ultimate database-ops benchmark](https://h2oai.github.io/db-benchmark/)
3. [Bogumił's Blog](https://bkamins.github.io/)
4. This tutorial series is _very_ good for the DataFrames.jl package: [https://github.com/bkamins/Julia-DataFrames-Tutorial](https://github.com/bkamins/Julia-DataFrames-Tutorial)
5. The [julia academy data science tutorial](https://github.com/JuliaAcademy/DataScience) is full of excellent stuff
6. The [Turing Institute's Data Sciences tutorials](https://alan-turing-institute.github.io/DataScienceTutorials.jl/) give a good intro to data structures and machine learning in julia.


