---
title: Homework 5
sidebar: homeworks
---

# Homework - Harold Zurcher

> How could we **not** talk about Harold Zurcher in this course!

First things first: Who was Harold Zurcher? *Generations* of Econ PhD students have heard about this man. Harold Zurcher even had a parody account on twitter, while twitter still existed. Why the fame? Well he was the leading actor in [John Rust's](https://editorialexpress.com/jrust/) groundbreaking paper on Bus Engine Replacement. Much of what we do nowadays in structural micro econometrics can be traced back to that paper. Even I have a [paper](https://www.sciencedirect.com/science/article/pii/S0165176512000870) on the Bus Engine Replacement Model!



### This homework is easy 🍿

In this very easy homework, I will outsource you to the phantastic video material of [Fedor Iskhakov](https://fedor.iskh.me/compecon). Fedor is among the world's leading experts of that model class - amongst other things - and therefore (trying to) redo what he did in his course is just pointless. We will next time in class implement the numerical solution in julia. Be sure to check out all the other great stuff that Fedor does [in his course](https://fedor.iskh.me/compecon).

**So, what's to do?**

* Watch the 45 minute video of Fedor [here](https://youtu.be/Yo69tlKKplY). It's full of relevant info beyond the Rust model at hand.


